[option]
exclude_paths = []
textwidth = 100
copyright_linenum = 1
copyright_year = "1234"
copyright_holder = "HOLDER"
indent = 2
prefix_inout = "b_"
prefix_input = "i_"
prefix_output = "o_"
prefix_label = "l_"
prefix_instance = "u"
prefix_module = "mod_"
prefix_package = "pkg_"
prefix_interface = "ifc_"
